const bicicletas = [
  { id: 1, nombre: "TrailBlazer X1", precio: 1428290, categoria: "montaña", proveedor: "Sport Pro", stock: 15 },
  { id: 2, nombre: "Urban Cruiser 3000", precio: 646631, categoria: "ciudad", proveedor: "City Wheels", stock: 25 },
  { id: 3, nombre: "Speedster Elite", precio: 668463, categoria: "carretera", proveedor: "Velocity Co.", stock: 10 },
  { id: 4, nombre: "Mountain King", precio: 1035996, categoria: "montaña", proveedor: "Sport Pro", stock: 30 },
  { id: 5, nombre: "Metro Glide", precio: 849520, categoria: "ciudad", proveedor: "City Wheels", stock: 20 },
  { id: 6, nombre: "Road Runner 500", precio: 531586, categoria: "carretera", proveedor: "Velocity Co.", stock: 12 },
  { id: 7, nombre: "TrailMaster 4X", precio: 902601, categoria: "montaña", proveedor: "Sport Pro", stock: 18 },
  { id: 8, nombre: "City Cruiser V2", precio: 336092, categoria: "ciudad", proveedor: "City Wheels", stock: 22 },
  { id: 9, nombre: "Sprint Supreme", precio: 826621, categoria: "carretera", proveedor: "Velocity Co.", stock: 8 },
  { id: 10, nombre: "Mountain Beast", precio: 889915, categoria: "montaña", proveedor: "Sport Pro", stock: 16 },
  { id: 11, nombre: "Urban Flyer", precio: 1121912, categoria: "ciudad", proveedor: "City Wheels", stock: 30 },
  { id: 12, nombre: "Velocity Tourer", precio: 1317685, categoria: "carretera", proveedor: "Velocity Co.", stock: 14 },
  { id: 13, nombre: "Eco Ride", precio: 883667, categoria: "ciudad", proveedor: "City Wheels", stock: 28 },
  { id: 14, nombre: "Swift Racer", precio: 682195, categoria: "carretera", proveedor: "Velocity Co.", stock: 7 },
  { id: 15, nombre: "Rock Master", precio: 506802, categoria: "montaña", proveedor: "Sport Pro", stock: 17 },
  { id: 16, nombre: "Eco Explorer", precio: 759832, categoria: "ciudad", proveedor: "Green Wheels", stock: 20 },
  { id: 17, nombre: "Speed King", precio: 1046573, categoria: "carretera", proveedor: "Velocity Co.", stock: 9 },
  { id: 18, nombre: "Mountain Conqueror", precio: 1204950, categoria: "montaña", proveedor: "Alpine Sports", stock: 13 },
  { id: 19, nombre: "Urban Swift", precio: 401239, categoria: "ciudad", proveedor: "City Wheels", stock: 24 },
  { id: 20, nombre: "Road Blaster", precio: 1132567, categoria: "carretera", proveedor: "Velocity Co.", stock: 11 },
  { id: 21, nombre: "Trail Blazer Pro", precio: 795467, categoria: "montaña", proveedor: "Sport Pro", stock: 15 },
  { id: 22, nombre: "City Sprint", precio: 372194, categoria: "ciudad", proveedor: "City Wheels", stock: 26 },
  { id: 23, nombre: "Velocity Racer", precio: 1403982, categoria: "carretera", proveedor: "Velocity Co.", stock: 10 },
  { id: 24, nombre: "Peak Master", precio: 1098765, categoria: "montaña", proveedor: "Alpine Sports", stock: 19 },
  { id: 25, nombre: "Eco Commuter", precio: 659882, categoria: "ciudad", proveedor: "Green Wheels", stock: 21 },
  { id: 26, nombre: "Mountain Cruiser", precio: 980412, categoria: "montaña", proveedor: "Sport Pro", stock: 14 },
  { id: 27, nombre: "Urban Rider", precio: 739299, categoria: "ciudad", proveedor: "City Wheels", stock: 27 },
  { id: 28, nombre: "Speed Chaser", precio: 1278943, categoria: "carretera", proveedor: "Velocity Co.", stock: 8 },
  { id: 29, nombre: "Trail Adventurer", precio: 876421, categoria: "montaña", proveedor: "Alpine Sports", stock: 22 },
  { id: 30, nombre: "City Explorer", precio: 475902, categoria: "ciudad", proveedor: "Green Wheels", stock: 18 },
  { id: 31, nombre: "Casco Pro", precio: 150000, categoria: "suplemento", proveedor: "Safety Gear", stock: 40 },
  { id: 32, nombre: "Guantes MTB", precio: 80000, categoria: "suplemento", proveedor: "Mountain Essentials", stock: 50 },
  { id: 33, nombre: "Luz Delantera LED", precio: 120000, categoria: "suplemento", proveedor: "Night Riders", stock: 60 },
  { id: 34, nombre: "Bomba de Aire Portátil", precio: 50000, categoria: "repuesto", proveedor: "BikeTools", stock: 100 },
  { id: 35, nombre: "Cadena de Repuesto", precio: 95000, categoria: "repuesto", proveedor: "Spare Parts Co.", stock: 75 },
  { id: 36, nombre: "Asiento Ergonómico", precio: 180000, categoria: "repuesto", proveedor: "Comfort Ride", stock: 30 },
  { id: 37, nombre: "Llantas Antipinchazo", precio: 220000, categoria: "repuesto", proveedor: "Tough Wheels", stock: 25 },
  { id: 38, nombre: "Botella de Agua Deportiva", precio: 25000, categoria: "suplemento", proveedor: "HydroSports", stock: 150 },
  { id: 39, nombre: "Portabicicletas", precio: 350000, categoria: "repuesto", proveedor: "BikeGear", stock: 20 },
  { id: 40, nombre: "Juego de Herramientas Multiuso", precio: 110000, categoria: "repuesto", proveedor: "BikeTools", stock: 50 }
];

